# -------------------------------------------
# levmar

IF(BUILD_LEVMAR)
    
    SET(LEVMAR_DIR ${CMAKE_CURRENT_SOURCE_DIR}/cmake/c/levmar)
    SET(LEVMAR_LIBRARY "levmar.lib")
    SET(LEVMAR_INCLUDE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/cmake/c)
    if(NOT EXISTS "${CMAKE_LIBRARY_OUTPUT_DIRECTORY}/levmar.lib")
      building_library("levmar")
      include(ExternalProject)

      ExternalProject_Add(levmar
		URL "${CMAKE_CURRENT_SOURCE_DIR}/cmake/archive/levmar-master.zip"
		SOURCE_DIR cmake/c/levmar
		BINARY_DIR cmake/c/levmar-build
		CMAKE_ARGS
		    -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}
		    -DCMAKE_RUNTIME_OUTPUT_DIRECTORY:PATH=${CMAKE_RUNTIME_OUTPUT_DIRECTORY}
		    -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE:PATH=${CMAKE_RUNTIME_OUTPUT_DIRECTORY}
		    -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG:PATH=${CMAKE_RUNTIME_OUTPUT_DIRECTORY}
		    -DCMAKE_LIBRARY_OUTPUT_DIRECTORY:PATH=${CMAKE_LIBRARY_OUTPUT_DIRECTORY}
		    -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE:PATH=${CMAKE_LIBRARY_OUTPUT_DIRECTORY}
		    -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG:PATH=${CMAKE_LIBRARY_OUTPUT_DIRECTORY}
		    -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY:PATH=${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}
		    -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE:PATH=${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}
		    -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG:PATH=${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}
		    -DBUILD_DEMO=OFF
		INSTALL_COMMAND ""
		)

    endif(NOT EXISTS "${CMAKE_LIBRARY_OUTPUT_DIRECTORY}/levmar.lib")
ENDIF(BUILD_LEVMAR)


