# -----------------------------------------------------------------------
# GSL
IF(BUILD_GSL)
    SET(GSL_INCLUDE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/cmake/c)
    SET(GSL_LIBRARY_DIR ${CMAKE_LIBRARY_OUTPUT_DIRECTORY})
    if(WIN32)
        SET(GSL_LIBRARY gsl.lib)
        SET(GSL_CBLAS_LIBRARY gslcblas.lib)
    else()
        SET(GSL_LIBRARY gsl)
        SET(GSL_CBLAS_LIBRARY gslcblas)
    endif()

    if(NOT EXISTS "${GSL_LIBRARY_DIR}/${GSL_LIBRARY}" OR
            NOT EXISTS "${GSL_LIBRARY_DIR}/${GSL_CBLAS_LIBRARY}")
        building_library("gsl")
        include(ExternalProject)

        ExternalProject_Add(gsl
		URL "${CMAKE_CURRENT_SOURCE_DIR}/cmake/archive/gsl-master.zip"
		SOURCE_DIR cmake/c/gsl
		BINARY_DIR cmake/c/gsl-build
		CMAKE_ARGS
		    -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}
		    -DCMAKE_RUNTIME_OUTPUT_DIRECTORY:PATH=${CMAKE_RUNTIME_OUTPUT_DIRECTORY}
		    -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE:PATH=${CMAKE_RUNTIME_OUTPUT_DIRECTORY}
		    -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG:PATH=${CMAKE_RUNTIME_OUTPUT_DIRECTORY}
		    -DCMAKE_LIBRARY_OUTPUT_DIRECTORY:PATH=${CMAKE_LIBRARY_OUTPUT_DIRECTORY}
		    -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE:PATH=${CMAKE_LIBRARY_OUTPUT_DIRECTORY}
		    -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG:PATH=${CMAKE_LIBRARY_OUTPUT_DIRECTORY}
		    -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY:PATH=${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}
		    -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE:PATH=${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}
		    -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG:PATH=${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}
		    -DGSL_DISABLE_WARNINGS=TRUE
		    -DGSL_DISABLE_TESTS=TRUE
		    -DGSL_INSTALL=FALSE
		INSTALL_COMMAND ""
		)
    endif()
    find_package(GSL REQUIRED)
    SET(CBLAS_INCLUDE_DIRS "${GSL_INCLUDE_DIR}/gsl/cblas")
    find_package(CBLAS)
ENDIF(BUILD_GSL)


