message("------------------------------------")
message("- Result")
message("------------------------------------")

find_package(LEVMAR)
include_directories(${LEVMAR_INCLUDE_DIR})
find_package(CLAPACK)
find_package(F2C)
include_directories(${F2C_INCLUDE_DIR})
find_package(LBFGS)
find_package(LetsBeRational)
find_package(OpenSSL)

message(STATUS "GSL ${GSL_FOUND}")
if(GSL_FOUND)
  message(" -- GSL_INCLUDE_DIRS : ${GSL_INCLUDE_DIRS}")
  message(" -- GSL_LIBRARY : ${GSL_LIBRARY}")
  message(" -- GSL_CBLAS_LIBRARY: ${GSL_CBLAS_LIBRARY}")
endif (GSL_FOUND)
message(STATUS "CLAPACK ${CLAPACK_FOUND}")
if (CLAPACK_FOUND)
  message(" -- CLAPACK_INCLUDE_DIRS : ${CLAPACK_INCLUDE_DIRS}")
  message(" -- CBLAS_INCLUDE_DIRS : ${CBLAS_INCLUDE_DIRS}")
  message(" -- CLAPACK_LIBRARIES : ${CLAPACK_LIBRARIES}")
endif (CLAPACK_FOUND)
message(STATUS "F2C ${F2C_FOUND}")
if (F2C_FOUND)
  message(" -- F2C_INCLUDE_DIRS : ${F2C_INCLUDE_DIRS}")
  message(" -- F2C_LIBRARY : ${F2C_LIBRARY}")
endif (F2C_FOUND)
message(STATUS "LBFGS ${LBFGS_FOUND}")
if (LBFGS_FOUND)
  message(" -- LBFGS_INCLUDE_DIRS : ${LBFGS_INCLUDE_DIRS}")
  message(" -- LBFGS_LIBRARY : ${LBFGS_LIBRARY}")
endif (LBFGS_FOUND)

message(STATUS "LetsBeRational ${LETSBERATIONAL_FOUND}")
if (LETSBERATIONAL_FOUND)
  message(" -- LETSBERATIONAL_INCLUDE_DIRS : ${LETSBERATIONAL_INCLUDE_DIRS}")
  message(" -- LETSBERATIONAL_LIBRARY : ${LETSBERATIONAL_LIBRARY}")
endif (LETSBERATIONAL_FOUND)

message(STATUS "Levmar ${LEVMAR_FOUND}")
if (LEVMAR_FOUND)
  message(" -- LEVMAR_INCLUDE_DIRS : ${LEVMAR_INCLUDE_DIRS}")
  message(" -- LEVMAR_LIBRARY : ${LEVMAR_LIBRARY}")
endif (LEVMAR_FOUND)


