# Find CLAPACK
# CLAPACK_INCLUDE_DIRS
# CLAPACK_LIBRARIES
# CLAPACK_FOUND

if(CLAPACK_FIND_QUIETLY)
  set(_FIND_CBLAS_ARG_QUIET)
endif(CLAPACK_FIND_QUIETLY)
find_package(CBLAS ${_FIND_CBLAS_ARG_QUIET})

if(CBLAS_FOUND)
	find_path(CLAPACK_INCLUDE_DIRS clapack.h)

	set(CLAPACK_NAMES ${CLAPACK_NAMES} lapack)
	find_library(CLAPACK_LIBRARY NAMES ${CLAPACK_NAMES})

endif(CBLAS_FOUND)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(CLAPACK DEFAULT_MSG CLAPACK_LIBRARY CLAPACK_INCLUDE_DIRS)

if(CLAPACK_FOUND)
  set(CLAPACK_INCLUDE_DIRS ${CLAPACK_INCLUDE_DIRS} ${CBLAS_INCLUDE_DIRS})
  set(CLAPACK_LIBRARIES ${CLAPACK_LIBRARY} ${CBLAS_LIBRARIES})
endif(CLAPACK_FOUND)

mark_as_advanced(CLAPACK_LIBRARY CLAPACK_INCLUDE_DIRS)

# add user defined
if( CLAPACK_FOUND AND NOT TARGET CLAPACK::lapack)
  add_library( CLAPACK::lapack UNKNOWN IMPORTED )
  set_target_properties( CLAPACK::lapack PROPERTIES
      IMPORTED_LOCATION                 "${CLAPACK_LIBRARY}"
      INTERFACE_INCLUDE_DIRECTORIES     "${CLAPACK_INCLUDE_DIRS}"
      IMPORTED_LINK_INTERFACE_LANGUAGES "C" )
endif()

if( CLAPACK_FOUND AND NOT TARGET CLAPACK::blas)
  add_library( CLAPACK::blas UNKNOWN IMPORTED )
  set_target_properties( CLAPACK::blas PROPERTIES
      IMPORTED_LOCATION                 "${CBLAS_LIBRARY}"
      INTERFACE_INCLUDE_DIRECTORIES     "${CBLAS_INCLUDE_DIRS}"
      IMPORTED_LINK_INTERFACE_LANGUAGES "C" )
endif()
